// Donnees extraites du PDF "programmes-gratuits-papa-muscle.pdf" (Methode AAA - Papa Muscle)
const PROGRAMS = [
  {
    id: 'perso_fullbody_abc',
    freq: 3,
    type: 'fonte',
    name: 'Mon programme - Full Body A/B/C',
    subtitle: 'Halteres - Tension / Hypertrophie / Volume',
    sessions: [
      { name: 'A - Tension', exercises: [
        { muscle: 'Quadriceps + fessiers', exo: 'Bulgarian split squat halteres', sets: '4 x 8-12 / jambe', rest: '90-120 s' },
        { muscle: 'Pectoraux', exo: 'Developpe couche halteres', sets: '4 x 8-15', rest: '2 min', note: 'Avec tes 34 kg, tu peux rester actuellement sur ton 4 x 12.' },
        { muscle: 'Dos', exo: 'Rowing halteres', sets: '4 x 8-15', rest: '90-120 s' },
        { muscle: 'Ischios + fessiers', exo: 'Souleve de terre roumain halteres', sets: '4 x 8-15', rest: '2 min' },
        { muscle: 'Epaules', exo: 'Elevations laterales', sets: '4 x 12-20', rest: '60-90 s' },
        { muscle: 'Biceps + triceps', exo: 'Curl + extension triceps en biset', sets: '4 x 10-15 chacun', rest: '60-90 s' },
      ]},
      { name: 'B - Hypertrophie', exercises: [
        { muscle: 'Quadriceps', exo: 'Goblet squat / squat halteres', sets: '4 x 12-20', rest: '90-120 s' },
        { muscle: 'Pectoraux (haut)', exo: 'Developpe incline halteres', sets: '4 x 8-15', rest: '2 min' },
        { muscle: 'Dos', exo: 'Rowing unilateral haltere', sets: '4 x 10-15 / cote', rest: '90 s' },
        { muscle: 'Quadriceps + fessiers', exo: 'Fentes arriere halteres', sets: '4 x 10-15 / jambe', rest: '90-120 s' },
        { muscle: 'Epaules', exo: 'Elevations laterales', sets: '4 x 15-20', rest: '60-90 s' },
        { muscle: 'Biceps + triceps', exo: 'Curl marteau + triceps en biset', sets: '4 x 10-15 chacun', rest: '60-90 s' },
      ]},
      { name: 'C - Volume / charges limitees', exercises: [
        { muscle: 'Quadriceps + fessiers', exo: 'Bulgarian split squat', sets: '4 x 12-15 / jambe', rest: '90 s' },
        { muscle: 'Pectoraux', exo: 'Developpe couche halteres', sets: '4 x 12-15', rest: '90-120 s' },
        { muscle: 'Dos', exo: 'Rowing poitrine appuyee', sets: '4 x 12-15', rest: '90 s' },
        { muscle: 'Fessiers', exo: 'Hip thrust haltere', sets: '4 x 12-20', rest: '90 s' },
        { muscle: 'Epaules', exo: 'Elevations laterales', sets: '4 x 15-25', rest: '60 s' },
        { muscle: 'Biceps + triceps', exo: 'Curl + triceps en biset', sets: '4 x 12-20 chacun', rest: '60-90 s' },
      ]},
    ],
  },
  {
    id: 'perso_half_ab_4j',
    freq: 4,
    type: 'fonte',
    name: 'Mon programme - Half A / Half B',
    subtitle: 'Halteres + elastique - lundi, mardi, jeudi, samedi',
    sessions: [
      { name: 'Lundi - Half A', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe couche halteres', sets: '4 x 6-10', rest: '90 s' },
        { muscle: 'Epaules', exo: 'Developpe epaules halteres', sets: '3 x 8-12', rest: '90 s' },
        { muscle: 'Dos', exo: 'Tirage vertical elastique', sets: '4 x 10-15', rest: '90 s' },
        { muscle: 'Epaules', exo: 'Elevations laterales', sets: '3 x 12-20', rest: '90 s' },
        { muscle: 'Biceps', exo: 'Curl halteres', sets: '3 x 8-12', rest: '90 s' },
        { muscle: 'Triceps', exo: 'Extension triceps elastique', sets: '3 x 10-15', rest: '90 s' },
      ]},
      { name: 'Mardi - Half B', exercises: [
        { muscle: 'Quadriceps + fessiers', exo: 'Bulgarian split squat', sets: '4 x 8-12 / jambe', rest: '90 s' },
        { muscle: 'Ischios + fessiers', exo: 'Souleve de terre roumain halteres', sets: '4 x 8-12', rest: '90 s' },
        { muscle: 'Dos', exo: 'Rowing haltere unilateral sur banc', sets: '4 x 8-12', rest: '90 s' },
        { muscle: 'Fessiers', exo: 'Hip thrust sur banc', sets: '3 x 10-15', rest: '90 s' },
        { muscle: 'Mollets', exo: 'Mollets avec halteres', sets: '3 x 12-20', rest: '90 s' },
        { muscle: 'Gainage', exo: 'Gainage', sets: '3 x 30-60 s', rest: '90 s' },
      ]},
      { name: 'Jeudi - Half A', exercises: [
        { muscle: 'Pectoraux (haut)', exo: 'Developpe incline halteres', sets: '4 x 8-12', rest: '90 s' },
        { muscle: 'Dos', exo: 'Tirage vertical elastique', sets: '4 x 10-15', rest: '90 s' },
        { muscle: 'Epaules', exo: 'Arnold press', sets: '3 x 8-12', rest: '90 s' },
        { muscle: 'Pectoraux', exo: 'Ecartes elastique ou halteres', sets: '3 x 12-15', rest: '90 s' },
        { muscle: 'Epaules', exo: 'Elevations laterales', sets: '3 x 15-20', rest: '90 s' },
        { muscle: 'Biceps + triceps', exo: 'Curl marteau + triceps elastique', sets: '3 x 10-15 chacun', rest: '90 s' },
      ]},
      { name: 'Samedi - Half B', exercises: [
        { muscle: 'Quadriceps', exo: 'Goblet squat haltere ou kettlebell', sets: '4 x 10-15', rest: '90 s' },
        { muscle: 'Quadriceps + fessiers', exo: 'Fentes arriere halteres', sets: '3 x 8-12 / jambe', rest: '90 s' },
        { muscle: 'Dos', exo: 'Rowing halteres poitrine sur banc incline', sets: '4 x 8-12', rest: '90 s' },
        { muscle: 'Ischios', exo: 'Souleve de terre roumain', sets: '3 x 10-12', rest: '90 s' },
        { muscle: 'Fessiers', exo: 'Hip thrust', sets: '3 x 10-15', rest: '90 s' },
        { muscle: 'Abdos', exo: 'Abdos', sets: '3 series', rest: '90 s' },
      ]},
    ],
  },
  {
    id: 'perso_bureau_elastiques',
    freq: 5,
    type: 'elastique',
    name: 'Mon programme - Bureau elastiques',
    subtitle: '1 serie par heure pendant les attentes - le programme du soir ne change pas',
    sessions: [
      { name: 'Menu A - soir BAS (haut du corps)', exercises: [
        { muscle: 'Dos', exo: 'Rowing penche', sets: '1 x 12-25', rest: '60 min', note: '1 serie par heure, 6 a 8 series dans la journee puis stop, un exercice par serie. 12 a 25 reps, arret 1 a 2 reps avant l echec : chaque serie doit etre dure. Plus de 25 reps : raccourcis la prise ou double l elastique. Note tes reps chaque jour (une ligne dans une note telephone).' },
        { muscle: 'Pectoraux', exo: 'Pompes elastiques', sets: '1 x 12-25', rest: '60 min' },
        { muscle: 'Epaules', exo: 'Developpe militaire', sets: '1 x 12-25', rest: '60 min' },
        { muscle: 'Arriere d epaules', exo: 'Pull-apart', sets: '1 x 12-25', rest: '60 min', note: 'Journee courte : fais seulement les 4 premieres, ce sont les plus importantes. Le frein : si tes seances du soir baissent, passe a 4 series par jour pendant une semaine. Jour de repos : menu A ou B au choix, ou rien.' },
        { muscle: 'Biceps', exo: 'Curl biceps', sets: '1 x 12-25', rest: '60 min' },
        { muscle: 'Triceps', exo: 'Extension triceps', sets: '1 x 12-25', rest: '60 min' },
        { muscle: 'Epaules', exo: 'Elevations laterales', sets: '1 x 12-25', rest: '60 min', note: 'Remplacant pour varier : rowing debout a la place des elevations laterales.' },
        { muscle: 'Posture', exo: 'Face pull', sets: '1 x 12-25', rest: '60 min' },
      ]},
      { name: 'Menu B - soir HAUT (jambes + posture)', exercises: [
        { muscle: 'Cuisses + fessiers', exo: 'Squat elastique', sets: '1 x 12-25', rest: '60 min', note: '1 serie par heure, 6 a 8 series dans la journee puis stop, un exercice par serie. 12 a 25 reps, arret 1 a 2 reps avant l echec : chaque serie doit etre dure. Plus de 25 reps : raccourcis la prise ou double l elastique. Note tes reps chaque jour (une ligne dans une note telephone).' },
        { muscle: 'Ischios + bas du dos', exo: 'Good morning', sets: '1 x 12-25', rest: '60 min' },
        { muscle: 'Cuisses + fessiers', exo: 'Fentes', sets: '1 x 12-25 / jambe', rest: '60 min' },
        { muscle: 'Posture', exo: 'Face pull', sets: '1 x 12-25', rest: '60 min', note: 'Journee courte : fais seulement les 4 premieres, ce sont les plus importantes. Le frein : si tes seances du soir baissent, passe a 4 series par jour pendant une semaine. Jour de repos : menu A ou B au choix, ou rien.' },
        { muscle: 'Cuisses + fessiers', exo: 'Squat elastique', sets: '1 x 12-25', rest: '60 min' },
        { muscle: 'Cuisses + fessiers', exo: 'Fentes', sets: '1 x 12-25 / jambe', rest: '60 min' },
        { muscle: 'Ischios + bas du dos', exo: 'Good morning', sets: '1 x 12-25', rest: '60 min' },
        { muscle: 'Arriere d epaules', exo: 'Pull-apart', sets: '1 x 12-25', rest: '60 min', note: 'Les jambes reviennent deux fois : c est voulu, la fiche n a que 3 exercices de jambes.' },
      ]},
    ],
  },
  {
    id: 'etirements_express_8',
    freq: 7,
    type: 'etirement',
    name: 'Etirements - Express 8 min',
    subtitle: 'Les six directions du dos + gainage - tous les jours',
    sessions: [
      { name: 'Express - 8 min', exercises: [
        { muscle: 'Flexion', exo: 'La boule', sets: '1 x 60 s', rest: '60 s', note: 'Sur le dos, genoux ramenes vers soi. La tete reste relachee : tu tires les genoux, pas la nuque.' },
        { muscle: 'Extension', exo: 'Le sphinx', sets: '1 x 60 s', rest: '60 s', note: 'Sur le ventre, buste redresse. Mains loin devant = plus doux, mains pres du bassin = plus intense. Fesses non serrees.' },
        { muscle: 'Inclinaison G + D', exo: 'Inclinaison au mur', sets: '2 x 45 s', rest: '45 s', note: 'Jambe exterieure croisee derriere, main haute accrochee, pousser le bassin sur le cote. Laisser la tete et le tronc se relacher.' },
        { muscle: 'Rotation G + D', exo: 'Torsion bord de lit', sets: '2 x 45 s', rest: '45 s', note: 'Sur le cote au bord du lit, bassin qui bascule vers le sol, tete tournee a l oppose. Sans mouvement brusque.' },
        { muscle: 'Chaine posterieure', exo: 'Pince tete en arriere', sets: '1 x 30 s', rest: '30 s', note: 'Assis jambes tendues, aller vers les pieds avec la tete legerement en ARRIERE. C est le muscle qu on vise, pas le nerf.' },
        { muscle: 'Gainage', exo: 'Bird dog', sets: '8 x 6 s / cote', rest: '6 s', note: 'Bras et jambe opposes, moins haut, abdos engages et bassin stable. La qualite compte plus que la hauteur.' },
      ]},
    ],
  },
  {
    id: 'etirements_complete_25',
    freq: 2,
    type: 'etirement',
    name: 'Etirements - Complete 25 min',
    subtitle: 'Quatre blocs : dos, hanches, mobilite et gainage, flow',
    sessions: [
      { name: 'Bloc A - le dos, six directions', exercises: [
        { muscle: 'Flexion', exo: 'La boule', sets: '1 x 90 s', rest: '90 s' },
        { muscle: 'Extension', exo: 'Le sphinx', sets: '1 x 90 s', rest: '90 s' },
        { muscle: 'Inclinaison G + D', exo: 'Inclinaison au mur', sets: '2 x 45 s', rest: '45 s' },
        { muscle: 'Rotation G + D', exo: 'Torsion bord de lit', sets: '2 x 45 s', rest: '45 s' },
      ]},
      { name: 'Bloc B - hanches et colonne', exercises: [
        { muscle: 'Chaine posterieure', exo: 'Flexion debout', sets: '1 x 30 s', rest: '30 s', note: 'Mains aux hanches, bassin en retroversion d abord, puis plonger.' },
        { muscle: 'Mise en tension nerveuse', exo: 'Flexion assise neurodynamique', sets: '10 mouvements doux', rest: '30 s', note: 'ATTENTION : tete en AVANT, c est le NERF qu on vise. Seul mouvement du document qui peut donner nausees, fatigue ou fourmillements. Doux, et jamais dans une seance faite vite.' },
        { muscle: 'Hanches', exo: 'Ouverture / fermeture de hanches', sets: '5 + 5', rest: '30 s', note: 'Assis, genoux ouverts puis fermes. Sert de transition.' },
        { muscle: 'Rotation', exo: 'Torsion assise', sets: '10 respirations x 2', rest: '60 s', note: 'Jambe croisee, coude sur le genou. A eviter en cas de prothese de hanche.' },
      ]},
      { name: 'Bloc C - mobilite et gainage', exercises: [
        { muscle: 'Mobilite globale', exo: 'Best stretch', sets: '6 x 6 s x 2 cotes', rest: '6 s', note: 'Fente basse, main au ciel, regard sur les doigts. On tient, on ne balance pas.' },
        { muscle: 'Hanches', exo: '90-90 version courte', sets: '20/40/60/80 % x 10 s puis 30 s a 100 %', rest: '30 s', note: 'Assis 90-90, contractions progressives, les deux sens et les deux cotes. Rien ne bouge. Le protocole integral ferait 7 min a lui seul.' },
        { muscle: 'Chaine posterieure', exo: 'Pince tete en arriere', sets: '1 x 30 s', rest: '30 s' },
        { muscle: 'Gainage', exo: 'Bird dog', sets: '10 x 6 s x 2 cotes', rest: '6 s' },
      ]},
      { name: 'Bloc D - le flow', exercises: [
        { muscle: 'Enchainement', exo: 'Hip hinge puis ours puis fleche', sets: '3 tours complets', rest: '60 s', note: 'Pour finir la seance.' },
      ]},
    ],
  },
  {
    id: 'etirements_bas_du_dos_12',
    freq: 3,
    type: 'etirement',
    name: 'Etirements - Bas du dos 12 min',
    subtitle: 'Les jours ou ca tire en bas - que des tenues passives',
    sessions: [
      { name: 'Bas du dos - 12 min', exercises: [
        { muscle: 'Flexion', exo: 'La boule', sets: '1 x 90 s', rest: '90 s' },
        { muscle: 'Flexion (variante)', exo: 'Flexion assise en deux temps', sets: '1 x 90 s', rest: '90 s' },
        { muscle: 'Extension', exo: 'Le sphinx', sets: '1 x 90 s', rest: '90 s' },
        { muscle: 'Inclinaison G + D', exo: 'Inclinaison au mur', sets: '2 x 90 s', rest: '90 s' },
        { muscle: 'Rotation G + D', exo: 'Torsion bord de lit', sets: '2 x 90 s', rest: '90 s' },
      ]},
    ],
  },
  {
    id: '3j_fonte',
    freq: 3,
    type: 'fonte',
    name: '3 jours - Fonte',
    subtitle: 'Full-Body (haltere, barre, machine)',
    sessions: [
      { name: 'Seance 1', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe couche haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing Yates', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Developpe Arnold', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension haltere au front', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios + fessiers', exo: 'Souleve de terre jambe tendue', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Reverse crunch', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 2', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe incline haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Tirage vertical', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Elevation laterale poulie basse', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl haltere prise marteau', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Dips machine', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Leg extension', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios + fessiers', exo: 'Hip thrust', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension assis', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Marche du fermier', sets: '4 x max', rest: '1min - 3min' },
      ]},
      { name: 'Seance 3', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe decline haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Goodmorning haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Oiseau a la poulie', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl pupitre', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension triceps derriere la nuque', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps + fessiers', exo: 'Presse a cuisse', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Leg curl allonge', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Hollow hold haltere', sets: '4 x max', rest: '1min' },
      ]},
    ],
  },
  {
    id: '3j_elastique',
    freq: 3,
    type: 'elastique',
    name: '3 jours - Elastique',
    subtitle: 'Full-Body (bandes elastiques)',
    sessions: [
      { name: 'Seance 1', exercises: [
        { muscle: 'Pectoraux', exo: 'Presse horizontale', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing horizontal', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Elevation laterale', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl biceps', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension derriere la nuque', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Front squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios + fessiers', exo: 'Souleve de terre jambe tendue', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Crunch elastique derriere', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 2', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe incline', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Pull down', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Face-pull', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl prise marteau', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Kickback', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Leg extension', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios + fessiers', exo: 'Releve de bassin', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension assis', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Pallof Press', sets: '4 x max', rest: '1min' },
      ]},
      { name: 'Seance 3', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe decline', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Goodmorning', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Developpe militaire', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl pupitre', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension des triceps', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps + fessiers', exo: 'Presse a cuisse', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Leg curl allonge', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Planche', sets: '4 x max', rest: '1min' },
      ]},
    ],
  },
  {
    id: '3j_pdc',
    freq: 3,
    type: 'pdc',
    name: '3 jours - Poids du corps',
    subtitle: 'Full-Body (sans materiel)',
    sessions: [
      { name: 'Seance 1', exercises: [
        { muscle: 'Pectoraux', exo: 'Pompe', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing inverse pronation', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Pompe piquee', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Traction supination', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension triceps au mur (ou barre)', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers + ischios', exo: 'Releve de bassin', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Reverse crunch', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 2', exercises: [
        { muscle: 'Pectoraux', exo: 'Pompe declinee', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Traction pronation', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Face-pull', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl biceps prise neutre', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Dips', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Fente', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers + ischios', exo: 'Kickback jambe', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension assis', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Planche laterale', sets: '4 x max', rest: '1min' },
      ]},
      { name: 'Seance 3', exercises: [
        { muscle: 'Pectoraux', exo: 'Pompe inclinee', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Extension lombaire au sol', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Elevation laterale au sol (ou au mur)', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl biceps', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Dips', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps + fessiers', exo: 'Pistol squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Nordic curl', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Gainage', sets: '4 x max', rest: '1min' },
      ]},
    ],
  },
  {
    id: '4j_fonte',
    freq: 4,
    type: 'fonte',
    name: '4 jours - Fonte',
    subtitle: 'Push / Pull / Legs / Full-Body (haltere, barre, machine)',
    sessions: [
      { name: 'Seance 1 - Push', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe couche haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Pectoraux', exo: 'Developpe incline haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Developpe Arnold', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Elevation laterale poulie basse', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension triceps derriere la nuque', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Dips machine', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Reverse crunch', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 2 - Pull', exercises: [
        { muscle: 'Dos', exo: 'Tirage vertical', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing Yates', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Goodmorning haltere', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Oiseau a la poulie', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl haltere prise marteau', sets: '3 x 8-12 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 3 - Legs', exercises: [
        { muscle: 'Quadriceps', exo: 'Squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Leg extension', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Souleve de terre jambe tendue', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Leg curl allonge', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers', exo: 'Hip thrust', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '5 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Marche du fermier', sets: '4 x max', rest: '1min' },
      ]},
      { name: 'Seance 4 - Full-Body', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe decline haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing haltere a un bras', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Tirage menton haltere', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl pupitre', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension haltere au front', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Presse a cuisse', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios + fessiers', exo: 'Souleve de terre jambe tendue', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension assis', sets: '5 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Hollow hold haltere', sets: '4 x max', rest: '1min' },
      ]},
    ],
  },
  {
    id: '4j_elastique',
    freq: 4,
    type: 'elastique',
    name: '4 jours - Elastique',
    subtitle: 'Push / Pull / Legs / Full-Body (bandes)',
    sessions: [
      { name: 'Seance 1 - Push', exercises: [
        { muscle: 'Pectoraux', exo: 'Presse horizontale', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Pectoraux', exo: 'Developpe incline', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Developpe militaire', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Elevation laterale', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension derriere la nuque', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Kickback', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Crunch elastique derriere', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 2 - Pull', exercises: [
        { muscle: 'Dos', exo: 'Pull down', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing horizontal', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Goodmorning', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Face-pull', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl biceps', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl prise marteau', sets: '3 x 8-12 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 3 - Legs', exercises: [
        { muscle: 'Quadriceps', exo: 'Front squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Leg extension', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Souleve de terre jambe tendue', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Leg curl allonge', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers', exo: 'Releve de bassin', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '5 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Pallof Press', sets: '4 x max', rest: '1min' },
      ]},
      { name: 'Seance 4 - Full-Body', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe decline', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing a un bras', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Tirage menton', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl pupitre', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension des triceps', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Presse a cuisse', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios + fessiers', exo: 'Souleve de terre jambe tendue', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension assis', sets: '5 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Gainage', sets: '4 x max', rest: '1min' },
      ]},
    ],
  },
  {
    id: '4j_pdc',
    freq: 4,
    type: 'pdc',
    name: '4 jours - Poids du corps',
    subtitle: 'Push / Pull / Legs / Full-Body (sans materiel)',
    sessions: [
      { name: 'Seance 1 - Push', exercises: [
        { muscle: 'Pectoraux', exo: 'Pompe', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Pectoraux', exo: 'Pompe inclinee', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Pompe piquee', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Elevation laterale au sol (ou au mur)', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Dips', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension triceps au mur (ou barre)', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Reverse crunch', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 2 - Pull', exercises: [
        { muscle: 'Dos', exo: 'Traction pronation', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing inverse supination', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Extension lombaire au sol', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Face-pull', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Traction supination', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl biceps prise neutre', sets: '3 x 8-12 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 3 - Legs', exercises: [
        { muscle: 'Quadriceps', exo: 'Squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Fente', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Souleve de terre roumain a 1 jambe', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Curl Nordic', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers', exo: 'Releve de bassin', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '5 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Planche laterale', sets: '4 x max', rest: '1min' },
      ]},
      { name: 'Seance 4 - Full-Body', exercises: [
        { muscle: 'Pectoraux', exo: 'Pompe declinee', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing inverse pronation', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Pompe piquee', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl biceps', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Dips sur banc', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Pistol squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers + ischios', exo: 'Releve de bassin', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension assis', sets: '5 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Planche', sets: '4 x max', rest: '1min' },
      ]},
    ],
  },
  {
    id: '5j_fonte',
    freq: 5,
    type: 'fonte',
    name: '5 jours - Fonte',
    subtitle: 'Push / Pull / Legs / Upper / Lower (haltere, barre, machine)',
    sessions: [
      { name: 'Seance 1 - Push', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe decline haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Pectoraux', exo: 'Developpe incline haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Developpe Arnold', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Elevation laterale poulie basse', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension triceps derriere la nuque', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Dips machine', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Reverse crunch', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 2 - Pull', exercises: [
        { muscle: 'Dos', exo: 'Tirage vertical', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing Yates', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Goodmorning haltere', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Oiseau a la poulie', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl haltere prise marteau', sets: '4 x 8-12 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 3 - Legs', exercises: [
        { muscle: 'Quadriceps', exo: 'Squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Leg extension', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Souleve de terre jambe tendue', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Leg curl allonge', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers', exo: 'Hip thrust', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 4 - Upper', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe couche haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing haltere a un bras', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Tirage menton', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl pupitre', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension triceps au front', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Marche du fermier', sets: '4 x max', rest: '1min' },
        { muscle: 'Abdos', exo: 'Hollow hold haltere', sets: '4 x max', rest: '1min' },
      ]},
      { name: 'Seance 5 - Lower', exercises: [
        { muscle: 'Quadriceps', exo: 'Presse a cuisse', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Curl Nordic inverse', sets: '3 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Leg curl assis', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers', exo: 'Kickback a la poulie', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension assis', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min' },
      ]},
    ],
  },
  {
    id: '5j_elastique',
    freq: 5,
    type: 'elastique',
    name: '5 jours - Elastique',
    subtitle: 'Push / Pull / Legs / Upper / Lower (bandes)',
    sessions: [
      { name: 'Seance 1 - Push', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe decline', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Pectoraux', exo: 'Developpe incline', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Developpe militaire', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Elevation laterale', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension derriere la nuque', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Kickback', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Crunch elastique derriere', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 2 - Pull', exercises: [
        { muscle: 'Dos', exo: 'Pull down', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing horizontal', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Goodmorning', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Face-pull', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl biceps', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl prise marteau', sets: '4 x 8-12 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 3 - Legs', exercises: [
        { muscle: 'Quadriceps', exo: 'Front squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Leg extension', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Souleve de terre jambe tendue', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Leg curl allonge', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers', exo: 'Releve de bassin', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 4 - Upper', exercises: [
        { muscle: 'Pectoraux', exo: 'Presse horizontale', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing a un bras', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Tirage menton', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl pupitre', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension des triceps', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Pallof Press', sets: '4 x max', rest: '1min' },
        { muscle: 'Abdos', exo: 'Planche', sets: '4 x max', rest: '1min' },
      ]},
      { name: 'Seance 5 - Lower', exercises: [
        { muscle: 'Quadriceps', exo: 'Presse a cuisse', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Curl Nordic inverse', sets: '3 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Leg curl assis', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers', exo: 'Kickback elastique', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension assis', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min' },
      ]},
    ],
  },
  {
    id: '5j_pdc',
    freq: 5,
    type: 'pdc',
    name: '5 jours - Poids du corps',
    subtitle: 'Push / Pull / Legs / Upper / Lower (sans materiel)',
    sessions: [
      { name: 'Seance 1 - Push', exercises: [
        { muscle: 'Pectoraux', exo: 'Pompe declinee', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Pectoraux', exo: 'Pompe inclinee', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Pompe piquee', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Elevation laterale au sol (ou au mur)', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension triceps au mur (ou barre)', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Dips', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Reverse crunch', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 2 - Pull', exercises: [
        { muscle: 'Dos', exo: 'Traction pronation', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing inverse supination', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Extension lombaire au sol', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Face-pull', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Traction supination', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl biceps prise neutre', sets: '4 x 8-12 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 3 - Legs', exercises: [
        { muscle: 'Quadriceps', exo: 'Squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Fente', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Souleve de terre roumain a 1 jambe', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Curl Nordic', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers', exo: 'Releve de bassin', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 4 - Upper', exercises: [
        { muscle: 'Pectoraux', exo: 'Pompe', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing inverse pronation', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Pompe piquee', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl biceps', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Dips', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Planche laterale', sets: '4 x max', rest: '1min' },
        { muscle: 'Abdos', exo: 'Planche', sets: '4 x max', rest: '1min' },
      ]},
      { name: 'Seance 5 - Lower', exercises: [
        { muscle: 'Quadriceps', exo: 'Pistol squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Curl Nordic inverse', sets: '3 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Curl Nordic', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers', exo: 'Kickback', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension assis', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min' },
      ]},
    ],
  },
];
