// Donnees extraites du PDF "programmes-gratuits-papa-muscle.pdf" (Methode AAA - Papa Muscle)
const PROGRAMS = [
  {
    id: 'perso_fullbody_abc',
    freq: 3,
    type: 'fonte',
    name: 'Mon programme - Full Body A/B/C',
    subtitle: 'Halteres - Tension / Hypertrophie / Volume',
    sessions: [
      { name: 'A - Tension', exercises: [
        { muscle: 'Quadriceps + fessiers', exo: 'Bulgarian split squat halteres', sets: '4 x 8-12 / jambe', rest: '90-120 s' },
        { muscle: 'Pectoraux', exo: 'Developpe couche halteres', sets: '4 x 8-15', rest: '2 min', note: 'Avec tes 34 kg, tu peux rester actuellement sur ton 4 x 12.' },
        { muscle: 'Dos', exo: 'Rowing halteres', sets: '4 x 8-15', rest: '90-120 s' },
        { muscle: 'Ischios + fessiers', exo: 'Souleve de terre roumain halteres', sets: '4 x 8-15', rest: '2 min' },
        { muscle: 'Epaules', exo: 'Elevations laterales', sets: '4 x 12-20', rest: '60-90 s' },
        { muscle: 'Biceps + triceps', exo: 'Curl + extension triceps en biset', sets: '4 x 10-15 chacun', rest: '60-90 s' },
      ]},
      { name: 'B - Hypertrophie', exercises: [
        { muscle: 'Quadriceps', exo: 'Goblet squat / squat halteres', sets: '4 x 12-20', rest: '90-120 s' },
        { muscle: 'Pectoraux (haut)', exo: 'Developpe incline halteres', sets: '4 x 8-15', rest: '2 min' },
        { muscle: 'Dos', exo: 'Rowing unilateral haltere', sets: '4 x 10-15 / cote', rest: '90 s' },
        { muscle: 'Quadriceps + fessiers', exo: 'Fentes arriere halteres', sets: '4 x 10-15 / jambe', rest: '90-120 s' },
        { muscle: 'Epaules', exo: 'Elevations laterales', sets: '4 x 15-20', rest: '60-90 s' },
        { muscle: 'Biceps + triceps', exo: 'Curl marteau + triceps en biset', sets: '4 x 10-15 chacun', rest: '60-90 s' },
      ]},
      { name: 'C - Volume / charges limitees', exercises: [
        { muscle: 'Quadriceps + fessiers', exo: 'Bulgarian split squat', sets: '4 x 12-15 / jambe', rest: '90 s' },
        { muscle: 'Pectoraux', exo: 'Developpe couche halteres', sets: '4 x 12-15', rest: '90-120 s' },
        { muscle: 'Dos', exo: 'Rowing poitrine appuyee', sets: '4 x 12-15', rest: '90 s' },
        { muscle: 'Fessiers', exo: 'Hip thrust haltere', sets: '4 x 12-20', rest: '90 s' },
        { muscle: 'Epaules', exo: 'Elevations laterales', sets: '4 x 15-25', rest: '60 s' },
        { muscle: 'Biceps + triceps', exo: 'Curl + triceps en biset', sets: '4 x 12-20 chacun', rest: '60-90 s' },
      ]},
    ],
  },
  {
    id: '3j_fonte',
    freq: 3,
    type: 'fonte',
    name: '3 jours - Fonte',
    subtitle: 'Full-Body (haltere, barre, machine)',
    sessions: [
      { name: 'Seance 1', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe couche haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing Yates', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Developpe Arnold', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension haltere au front', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios + fessiers', exo: 'Souleve de terre jambe tendue', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Reverse crunch', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 2', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe incline haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Tirage vertical', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Elevation laterale poulie basse', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl haltere prise marteau', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Dips machine', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Leg extension', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios + fessiers', exo: 'Hip thrust', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension assis', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Marche du fermier', sets: '4 x max', rest: '1min - 3min' },
      ]},
      { name: 'Seance 3', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe decline haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Goodmorning haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Oiseau a la poulie', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl pupitre', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension triceps derriere la nuque', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps + fessiers', exo: 'Presse a cuisse', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Leg curl allonge', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Hollow hold haltere', sets: '4 x max', rest: '1min' },
      ]},
    ],
  },
  {
    id: '3j_elastique',
    freq: 3,
    type: 'elastique',
    name: '3 jours - Elastique',
    subtitle: 'Full-Body (bandes elastiques)',
    sessions: [
      { name: 'Seance 1', exercises: [
        { muscle: 'Pectoraux', exo: 'Presse horizontale', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing horizontal', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Elevation laterale', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl biceps', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension derriere la nuque', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Front squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios + fessiers', exo: 'Souleve de terre jambe tendue', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Crunch elastique derriere', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 2', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe incline', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Pull down', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Face-pull', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl prise marteau', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Kickback', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Leg extension', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios + fessiers', exo: 'Releve de bassin', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension assis', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Pallof Press', sets: '4 x max', rest: '1min' },
      ]},
      { name: 'Seance 3', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe decline', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Goodmorning', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Developpe militaire', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl pupitre', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension des triceps', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps + fessiers', exo: 'Presse a cuisse', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Leg curl allonge', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Planche', sets: '4 x max', rest: '1min' },
      ]},
    ],
  },
  {
    id: '3j_pdc',
    freq: 3,
    type: 'pdc',
    name: '3 jours - Poids du corps',
    subtitle: 'Full-Body (sans materiel)',
    sessions: [
      { name: 'Seance 1', exercises: [
        { muscle: 'Pectoraux', exo: 'Pompe', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing inverse pronation', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Pompe piquee', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Traction supination', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension triceps au mur (ou barre)', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers + ischios', exo: 'Releve de bassin', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Reverse crunch', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 2', exercises: [
        { muscle: 'Pectoraux', exo: 'Pompe declinee', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Traction pronation', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Face-pull', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl biceps prise neutre', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Dips', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Fente', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers + ischios', exo: 'Kickback jambe', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension assis', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Planche laterale', sets: '4 x max', rest: '1min' },
      ]},
      { name: 'Seance 3', exercises: [
        { muscle: 'Pectoraux', exo: 'Pompe inclinee', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Extension lombaire au sol', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Elevation laterale au sol (ou au mur)', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl biceps', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Dips', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps + fessiers', exo: 'Pistol squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Nordic curl', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Gainage', sets: '4 x max', rest: '1min' },
      ]},
    ],
  },
  {
    id: '4j_fonte',
    freq: 4,
    type: 'fonte',
    name: '4 jours - Fonte',
    subtitle: 'Push / Pull / Legs / Full-Body (haltere, barre, machine)',
    sessions: [
      { name: 'Seance 1 - Push', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe couche haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Pectoraux', exo: 'Developpe incline haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Developpe Arnold', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Elevation laterale poulie basse', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension triceps derriere la nuque', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Dips machine', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Reverse crunch', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 2 - Pull', exercises: [
        { muscle: 'Dos', exo: 'Tirage vertical', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing Yates', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Goodmorning haltere', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Oiseau a la poulie', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl haltere prise marteau', sets: '3 x 8-12 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 3 - Legs', exercises: [
        { muscle: 'Quadriceps', exo: 'Squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Leg extension', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Souleve de terre jambe tendue', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Leg curl allonge', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers', exo: 'Hip thrust', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '5 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Marche du fermier', sets: '4 x max', rest: '1min' },
      ]},
      { name: 'Seance 4 - Full-Body', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe decline haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing haltere a un bras', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Tirage menton haltere', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl pupitre', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension haltere au front', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Presse a cuisse', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios + fessiers', exo: 'Souleve de terre jambe tendue', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension assis', sets: '5 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Hollow hold haltere', sets: '4 x max', rest: '1min' },
      ]},
    ],
  },
  {
    id: '4j_elastique',
    freq: 4,
    type: 'elastique',
    name: '4 jours - Elastique',
    subtitle: 'Push / Pull / Legs / Full-Body (bandes)',
    sessions: [
      { name: 'Seance 1 - Push', exercises: [
        { muscle: 'Pectoraux', exo: 'Presse horizontale', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Pectoraux', exo: 'Developpe incline', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Developpe militaire', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Elevation laterale', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension derriere la nuque', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Kickback', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Crunch elastique derriere', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 2 - Pull', exercises: [
        { muscle: 'Dos', exo: 'Pull down', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing horizontal', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Goodmorning', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Face-pull', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl biceps', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl prise marteau', sets: '3 x 8-12 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 3 - Legs', exercises: [
        { muscle: 'Quadriceps', exo: 'Front squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Leg extension', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Souleve de terre jambe tendue', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Leg curl allonge', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers', exo: 'Releve de bassin', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '5 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Pallof Press', sets: '4 x max', rest: '1min' },
      ]},
      { name: 'Seance 4 - Full-Body', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe decline', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing a un bras', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Tirage menton', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl pupitre', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension des triceps', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Presse a cuisse', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios + fessiers', exo: 'Souleve de terre jambe tendue', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension assis', sets: '5 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Gainage', sets: '4 x max', rest: '1min' },
      ]},
    ],
  },
  {
    id: '4j_pdc',
    freq: 4,
    type: 'pdc',
    name: '4 jours - Poids du corps',
    subtitle: 'Push / Pull / Legs / Full-Body (sans materiel)',
    sessions: [
      { name: 'Seance 1 - Push', exercises: [
        { muscle: 'Pectoraux', exo: 'Pompe', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Pectoraux', exo: 'Pompe inclinee', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Pompe piquee', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Elevation laterale au sol (ou au mur)', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Dips', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension triceps au mur (ou barre)', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Reverse crunch', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 2 - Pull', exercises: [
        { muscle: 'Dos', exo: 'Traction pronation', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing inverse supination', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Extension lombaire au sol', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Face-pull', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Traction supination', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl biceps prise neutre', sets: '3 x 8-12 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 3 - Legs', exercises: [
        { muscle: 'Quadriceps', exo: 'Squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Fente', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Souleve de terre roumain a 1 jambe', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Curl Nordic', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers', exo: 'Releve de bassin', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '5 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Planche laterale', sets: '4 x max', rest: '1min' },
      ]},
      { name: 'Seance 4 - Full-Body', exercises: [
        { muscle: 'Pectoraux', exo: 'Pompe declinee', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing inverse pronation', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Pompe piquee', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl biceps', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Dips sur banc', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Pistol squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers + ischios', exo: 'Releve de bassin', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension assis', sets: '5 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Planche', sets: '4 x max', rest: '1min' },
      ]},
    ],
  },
  {
    id: '5j_fonte',
    freq: 5,
    type: 'fonte',
    name: '5 jours - Fonte',
    subtitle: 'Push / Pull / Legs / Upper / Lower (haltere, barre, machine)',
    sessions: [
      { name: 'Seance 1 - Push', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe decline haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Pectoraux', exo: 'Developpe incline haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Developpe Arnold', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Elevation laterale poulie basse', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension triceps derriere la nuque', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Dips machine', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Reverse crunch', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 2 - Pull', exercises: [
        { muscle: 'Dos', exo: 'Tirage vertical', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing Yates', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Goodmorning haltere', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Oiseau a la poulie', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl haltere prise marteau', sets: '4 x 8-12 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 3 - Legs', exercises: [
        { muscle: 'Quadriceps', exo: 'Squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Leg extension', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Souleve de terre jambe tendue', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Leg curl allonge', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers', exo: 'Hip thrust', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 4 - Upper', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe couche haltere', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing haltere a un bras', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Tirage menton', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl pupitre', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension triceps au front', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Marche du fermier', sets: '4 x max', rest: '1min' },
        { muscle: 'Abdos', exo: 'Hollow hold haltere', sets: '4 x max', rest: '1min' },
      ]},
      { name: 'Seance 5 - Lower', exercises: [
        { muscle: 'Quadriceps', exo: 'Presse a cuisse', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Curl Nordic inverse', sets: '3 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Leg curl assis', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers', exo: 'Kickback a la poulie', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension assis', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min' },
      ]},
    ],
  },
  {
    id: '5j_elastique',
    freq: 5,
    type: 'elastique',
    name: '5 jours - Elastique',
    subtitle: 'Push / Pull / Legs / Upper / Lower (bandes)',
    sessions: [
      { name: 'Seance 1 - Push', exercises: [
        { muscle: 'Pectoraux', exo: 'Developpe decline', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Pectoraux', exo: 'Developpe incline', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Developpe militaire', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Elevation laterale', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension derriere la nuque', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Kickback', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Crunch elastique derriere', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 2 - Pull', exercises: [
        { muscle: 'Dos', exo: 'Pull down', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing horizontal', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Goodmorning', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Face-pull', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl biceps', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl prise marteau', sets: '4 x 8-12 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 3 - Legs', exercises: [
        { muscle: 'Quadriceps', exo: 'Front squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Leg extension', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Souleve de terre jambe tendue', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Leg curl allonge', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers', exo: 'Releve de bassin', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 4 - Upper', exercises: [
        { muscle: 'Pectoraux', exo: 'Presse horizontale', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing a un bras', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Tirage menton', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl pupitre', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension des triceps', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Pallof Press', sets: '4 x max', rest: '1min' },
        { muscle: 'Abdos', exo: 'Planche', sets: '4 x max', rest: '1min' },
      ]},
      { name: 'Seance 5 - Lower', exercises: [
        { muscle: 'Quadriceps', exo: 'Presse a cuisse', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Curl Nordic inverse', sets: '3 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Leg curl assis', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers', exo: 'Kickback elastique', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension assis', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min' },
      ]},
    ],
  },
  {
    id: '5j_pdc',
    freq: 5,
    type: 'pdc',
    name: '5 jours - Poids du corps',
    subtitle: 'Push / Pull / Legs / Upper / Lower (sans materiel)',
    sessions: [
      { name: 'Seance 1 - Push', exercises: [
        { muscle: 'Pectoraux', exo: 'Pompe declinee', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Pectoraux', exo: 'Pompe inclinee', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Pompe piquee', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Elevation laterale au sol (ou au mur)', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Extension triceps au mur (ou barre)', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Dips', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Reverse crunch', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 2 - Pull', exercises: [
        { muscle: 'Dos', exo: 'Traction pronation', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing inverse supination', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Extension lombaire au sol', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Face-pull', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Traction supination', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl biceps prise neutre', sets: '4 x 8-12 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 3 - Legs', exercises: [
        { muscle: 'Quadriceps', exo: 'Squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Fente', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Souleve de terre roumain a 1 jambe', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Curl Nordic', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers', exo: 'Releve de bassin', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min - 3min' },
      ]},
      { name: 'Seance 4 - Upper', exercises: [
        { muscle: 'Pectoraux', exo: 'Pompe', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Dos', exo: 'Rowing inverse pronation', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Epaules', exo: 'Pompe piquee', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Biceps', exo: 'Curl biceps', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Triceps', exo: 'Dips', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Abdos', exo: 'Planche laterale', sets: '4 x max', rest: '1min' },
        { muscle: 'Abdos', exo: 'Planche', sets: '4 x max', rest: '1min' },
      ]},
      { name: 'Seance 5 - Lower', exercises: [
        { muscle: 'Quadriceps', exo: 'Pistol squat', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Quadriceps', exo: 'Curl Nordic inverse', sets: '3 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Ischios', exo: 'Curl Nordic', sets: '3 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Fessiers', exo: 'Kickback', sets: '4 x 8-12 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension assis', sets: '4 x 10-15 reps', rest: '1min - 3min' },
        { muscle: 'Mollets', exo: 'Extension debout', sets: '4 x 10-15 reps', rest: '1min' },
      ]},
    ],
  },
];
